<a href="https://colab.research.google.com/github/omkarmohite123/Companies_Problem-solving-using-Python/blob/main/Python_For_Data_Science_Python_Data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 5: Python Data Structures


In [ ]:
!pip install xlsxwriter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.8/152.8 KB 4.5 MB/s eta 0:00:00


In [ ]:
import xlsxwriter
workbook=xlsxwriter.Workbook('/content/ram.xlsx')  #/content/sample_data/california_housing_test.csv
work_ram=workbook.add_worksheet('data')

In [ ]:
workbook.close

<bound method Workbook.close of <xlsxwriter.workbook.Workbook object at 0x7f7f165ecfa0>>

In [ ]:
from openpyxl.reader.excel import load_workbook
wb = load_workbook(filename="ram.xlsx")



FileNotFoundError: ignored

## 5.1 Use lists and tuples

### Sequences
Lists, tuples, and strings are all Python sequences, and share many of the same methods.

### Creating an empty list

In [ ]:
empty = []
empty

[]

### Using square brackets with initial values

In [ ]:
numbers = [1, 2, 3]
numbers


[1, 2, 3]

### Casting an iterable
Any iterable can be cast to a list

In [ ]:
numbers = list(range(10))
numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### Creating using multiplication

In [ ]:
num_players = 10
scores = [0] * num_players
scores

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

### Mixing data types
Lists can contain multple data types

In [ ]:
mixed = ['a', 1, 2.0, [13], {}]
mixed

['a', 1, 2.0, [13], {}]

### Indexing
Items in lists can be accessed using indices in a similar fashion to strings.

#### Access first item

In [ ]:
numbers[0]


0

#### Access last item

In [ ]:
numbers[-2]

8

#### Access any item

In [ ]:
numbers[4]

4

### Adding to a list

#### Append to the end of a list

In [ ]:
letters = ['a']
letters.append('c')
letters

['a', 'c']

#### Insert at beginning of list

In [ ]:
letters.insert(0, 'b')
letters

['b', 'a', 'c']

#### Insert at arbitrary position

In [ ]:
letters.insert(2, 'c')
letters

['b', 'a', 'c', 'c']

#### Extending with another list

In [ ]:
more_letters = ['e', 'f', 'g']
letters.extend(more_letters)
letters

['b', 'a', 'c', 'c', 'e', 'f', 'g']

### Change item at some position

In [ ]:
letters[3] = 'd'
letters

['b', 'a', 'c', 'd', 'e', 'f', 'g']

In [ ]:
import numpy as np
arr=np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr=np.random.randint(1,100,10)
print(arr)

[ 8 10 37  3 79 63 43  4 32  8]


In [ ]:
arr=np.arange(10,35)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34]


In [ ]:
arr=np.ones(10)*4
print(arr)

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]


In [ ]:
arr=np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr=np.random.randint(1,100,10)
print(arr)
arr[arr%2==0]=1
print(arr)

[50  1 33 79 93 22 42 72 76 38]
[ 1  1 33 79 93  1  1  1  1  1]


In [ ]:
arr=np.random.rand(9).reshape(3,3)
print(arr)

[[0.85649518 0.81559934 0.1189305 ]
 [0.26936891 0.38596095 0.3745923 ]
 [0.79775857 0.67877482 0.40480988]]


In [ ]:
arr=np.arange(1,26).reshape(5,5)
print(arr)
arr=arr[4:,1:3]
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[22 23]]


In [ ]:
arr1=np.arange(1,10).reshape(3,3)
print(arr1)

arr2=np.arange(10,19).reshape(3,3)
print(arr2)
arr=np.hstack((arr1,arr2))
print(arr)
arr=np.vstack((arr1,arr2))
print(arr)




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/sample_data/california_housing_train.csv")

In [ ]:
df.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [ ]:
df.tail(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB


In [ ]:
df.shape

(17000, 9)

In [ ]:
df.size

153000

In [ ]:
df.sample(n=15)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2457     -117.60     33.65                 4.0       3134.0           504.0   
3737     -117.93     33.85                31.0       2149.0           465.0   
11077    -120.99     39.22                16.0       1497.0           275.0   
8373     -118.46     33.99                37.0       1828.0           460.0   
7324     -118.34     33.90                37.0        542.0           105.0   
7965     -118.41     34.04                52.0       2113.0           332.0   
5944     -118.21     34.05                28.0       1841.0           809.0   
16085    -122.45     37.71                50.0       1441.0           283.0   
15280    -122.28     37.87                46.0       3022.0           696.0   
2462     -117.61     34.14                14.0      15809.0          2485.0   
9057     -118.98     35.39                22.0       1812.0           457.0   
12781    -121.80     38.67                10.0       2086.0           380.0   
405      -116.95     33.76                10.0       6890.0          1702.0   
10194    -119.86     34.38                28.0       1062.0           309.0   
1068     -117.11     32.81                15.0       3428.0           491.0   

       population  households  median_income  median_house_value  
2457       1599.0       485.0         6.2464            233900.0  
3737        966.0       302.0         3.8750            183900.0  
11077       737.0       243.0         2.8942            182500.0  
8373       1075.0       453.0         4.3370            360600.0  
7324        355.0       118.0         5.5133            227300.0  
7965        800.0       327.0        11.1768            500001.0  
5944       3199.0       727.0         1.6319            151600.0  
16085      1159.0       286.0         4.5417            233700.0  
15280      1293.0       675.0         2.5430            220700.0  
2462       7363.0      2410.0         5.5198            245600.0  
9057       1592.0       420.0         1.4146             49100.0  
12781      1073.0       378.0         4.5526            154400.0  
405        3141.0      1451.0         1.7079             95900.0  
10194      1058.0       305.0         1.5071            316700.0  
1068       2303.0       486.0         2.5953             67500.0

In [ ]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [ ]:
df.describe().T

count           mean            std         min  \
longitude           17000.0    -119.562108       2.005166   -124.3500   
latitude            17000.0      35.625225       2.137340     32.5400   
housing_median_age  17000.0      28.589353      12.586937      1.0000   
total_rooms         17000.0    2643.664412    2179.947071      2.0000   
total_bedrooms      17000.0     539.410824     421.499452      1.0000   
population          17000.0    1429.573941    1147.852959      3.0000   
households          17000.0     501.221941     384.520841      1.0000   
median_income       17000.0       3.883578       1.908157      0.4999   
median_house_value  17000.0  207300.912353  115983.764387  14999.0000   

                              25%          50%         75%          max  
longitude             -121.790000    -118.4900    -118.000    -114.3100  
latitude                33.930000      34.2500      37.720      41.9500  
housing_median_age      18.000000      29.0000      37.000      52.0000  
total_rooms           1462.000000    2127.0000    3151.250   37937.0000  
total_bedrooms         297.000000     434.0000     648.250    6445.0000  
population             790.000000    1167.0000    1721.000   35682.0000  
households             282.000000     409.0000     605.250    6082.0000  
median_income            2.566375       3.5446       4.767      15.0001  
median_house_value  119400.000000  180400.0000  265000.000  500001.0000

In [ ]:
df.nunique()

longitude               827
latitude                840
housing_median_age       52
total_rooms            5533
total_bedrooms         1848
population             3683
households             1740
median_income         11175
median_house_value     3694
dtype: int64

In [ ]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
df.isnull().any()

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms        False
population            False
households            False
median_income         False
median_house_value    False
dtype: bool

In [ ]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
df.nsmallest(10,'population')

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8232     -118.44     34.04                16.0         18.0             6.0   
2990     -117.79     35.21                 4.0          2.0             2.0   
2907     -117.76     35.22                 4.0         18.0             3.0   
14105    -122.06     37.39                26.0         18.0             4.0   
288      -116.76     34.14                 4.0         42.0            10.0   
10911    -120.85     37.75                26.0         28.0             4.0   
15656    -122.37     37.60                26.0         15.0             3.0   
1466     -117.19     32.75                52.0         25.0             5.0   
10356    -120.13     35.87                26.0         48.0             8.0   
14501    -122.14     37.50                46.0         30.0             4.0   

       population  households  median_income  median_house_value  
8232          3.0         4.0         0.5360            350000.0  
2990          6.0         2.0         2.3750            137500.0  
2907          8.0         6.0         1.6250            275000.0  
14105         8.0         4.0         3.7500            375000.0  
288           9.0         3.0         0.5360             42500.0  
10911         9.0         5.0         1.6250             85000.0  
15656        11.0         3.0         5.0480            350000.0  
1466         13.0         5.0         0.5360            162500.0  
10356        13.0         8.0         2.3750             71300.0  
14501        13.0         5.0        15.0001            500001.0

In [ ]:
df.nlargest(10,'population')

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2274     -117.42     33.35                14.0      25135.0          4819.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
2871     -117.74     33.89                 4.0      37937.0          5471.0   
2969     -117.78     34.03                 8.0      32054.0          5290.0   
3296     -117.87     34.04                 7.0      27700.0          4179.0   
1116     -117.12     33.52                 4.0      30401.0          4957.0   
8881     -118.78     34.16                 9.0      30405.0          4093.0   
10692    -120.59     34.70                29.0      17738.0          3114.0   
13299    -121.92     37.53                 7.0      28258.0          3864.0   
12586    -121.68     36.72                12.0      19234.0          4492.0   

       population  households  median_income  median_house_value  
2274      35682.0      4769.0         2.5729            134400.0  
12772     28566.0      6082.0         2.3087            118800.0  
2871      16122.0      5189.0         7.4947            366300.0  
2969      15507.0      5050.0         6.0191            253900.0  
3296      15037.0      4072.0         6.6288            339700.0  
1116      13251.0      4339.0         4.5841            212300.0  
8881      12873.0      3931.0         8.0137            399200.0  
10692     12427.0      2826.0         2.7377             28300.0  
13299     12203.0      3701.0         8.4045            451100.0  
12586     12153.0      4372.0         3.2652            152800.0

In [ ]:
df.loc[10:30,['population','latitude']]

population  latitude
10      2434.0     33.62
11      1182.0     33.60
12       580.0     34.84
13      1346.0     34.83
14       949.0     32.76
15      1005.0     34.89
16       666.0     33.60
17        64.0     32.79
18       775.0     32.74
19        29.0     33.92
20      1135.0     33.49
21       227.0     33.43
22       119.0     34.55
23       137.0     33.82
24      3424.0     33.54
25       327.0     32.82
26      1130.0     32.82
27       867.0     32.82
28       623.0     32.81
29       866.0     32.81
30      1175.0     32.82

In [ ]:
df.iloc[10:30,[5,1]]

population  latitude
10      2434.0     33.62
11      1182.0     33.60
12       580.0     34.84
13      1346.0     34.83
14       949.0     32.76
15      1005.0     34.89
16       666.0     33.60
17        64.0     32.79
18       775.0     32.74
19        29.0     33.92
20      1135.0     33.49
21       227.0     33.43
22       119.0     34.55
23       137.0     33.82
24      3424.0     33.54
25       327.0     32.82
26      1130.0     32.82
27       867.0     32.82
28       623.0     32.81
29       866.0     32.81

In [ ]:
df.iloc[10:15,[1,2,5]]

latitude  housing_median_age  population
10     33.62                16.0      2434.0
11     33.60                21.0      1182.0
12     34.84                48.0       580.0
13     34.83                31.0      1346.0
14     32.76                15.0       949.0

In [ ]:
df[10:12]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
10     -114.6     33.62                16.0       3741.0           801.0   
11     -114.6     33.60                21.0       1988.0           483.0   

    population  households  median_income  median_house_value  
10      2434.0       824.0         2.6797             86500.0  
11      1182.0       437.0         1.6250             62000.0

In [ ]:
df[['total_rooms','total_bedrooms']].groupby(df['housing_median_age']).sum()

total_rooms  total_bedrooms
housing_median_age                             
1.0                      4316.0           671.0
2.0                    256618.0         42701.0
3.0                    318335.0         54778.0
4.0                    976564.0        171979.0
5.0                    980326.0        181274.0
6.0                    563093.0        105980.0
7.0                    856609.0        158150.0
8.0                    725668.0        138707.0
9.0                    655916.0        125113.0
10.0                   795177.0        154021.0
11.0                   825990.0        159938.0
12.0                   809599.0        161058.0
13.0                   919434.0        179198.0
14.0                  1290961.0        249558.0
15.0                  1365860.0        268525.0
16.0                  1935249.0        376729.0
17.0                  1805165.0        365622.0
18.0                  1481056.0        298523.0
19.0                  1238118.0        256066.0
20.0                  1092444.0        230481.0
21.0                  1169084.0        240812.0
22.0                  1071364.0        220847.0
23.0                  1114983.0        223250.0
24.0                  1125823.0        235208.0
25.0                  1289537.0        267961.0
26.0                  1314042.0        263544.0
27.0                  1023230.0        214368.0
28.0                  1015352.0        216283.0
29.0                   929040.0        197642.0
30.0                   901190.0        196336.0
31.0                   900543.0        195000.0
32.0                  1079002.0        224198.0
33.0                  1131366.0        232694.0
34.0                  1209201.0        246639.0
35.0                  1363103.0        279690.0
36.0                  1319687.0        269616.0
37.0                   795180.0        169204.0
38.0                   587978.0        128024.0
39.0                   569853.0        124770.0
40.0                   454067.0        101651.0
41.0                   383617.0         87208.0
42.0                   539116.0        122039.0
43.0                   481594.0        109484.0
44.0                   528559.0        113176.0
45.0                   420859.0         88373.0
46.0                   340554.0         76377.0
47.0                   311580.0         67935.0
48.0                   239962.0         51219.0
49.0                   214049.0         44828.0
50.0                   197001.0         44205.0
51.0                    59890.0         12469.0
52.0                  1965391.0        425862.0

In [ ]:
df['mult']=df['total_rooms']*df['total_bedrooms']

In [ ]:
df['mult'].head(10)

0     7200196.0
1    14542650.0
2      125280.0
3      505837.0
4      474004.0
5      327332.0
6     1976760.0
7      136416.0
8     5627075.0
9      462573.0
Name: mult, dtype: float64

In [ ]:
df.sort_values(by='total_rooms',ascending=False)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2871     -117.74     33.89                 4.0      37937.0          5471.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
2969     -117.78     34.03                 8.0      32054.0          5290.0   
8881     -118.78     34.16                 9.0      30405.0          4093.0   
1116     -117.12     33.52                 4.0      30401.0          4957.0   
...          ...       ...                 ...          ...             ...   
4502     -118.04     33.90                36.0         15.0             5.0   
15369    -122.29     37.81                46.0         12.0             4.0   
8188     -118.44     34.28                46.0         11.0            11.0   
16309    -122.50     37.79                52.0          8.0             1.0   
2990     -117.79     35.21                 4.0          2.0             2.0   

       population  households  median_income  median_house_value         mult  
2871      16122.0      5189.0         7.4947            366300.0  207553327.0  
12772     28566.0      6082.0         2.3087            118800.0  210281015.0  
2969      15507.0      5050.0         6.0191            253900.0  169565660.0  
8881      12873.0      3931.0         8.0137            399200.0  124447665.0  
1116      13251.0      4339.0         4.5841            212300.0  150697757.0  
...           ...         ...            ...                 ...          ...  
4502         15.0         6.0         0.4999            162500.0         75.0  
15369        18.0         7.0         0.4999             67500.0         48.0  
8188         24.0        13.0         2.8750            162500.0        121.0  
16309        13.0         1.0        15.0001            500001.0          8.0  
2990          6.0         2.0         2.3750            137500.0          4.0  

[17000 rows x 10 columns]

In [ ]:
df.query('latitude > 41')

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
10315    -120.08     41.79                34.0       1355.0           262.0   
10348    -120.12     41.40                33.0       2820.0           515.0   
10620    -120.48     41.82                20.0       1367.0           284.0   
10656    -120.55     41.61                22.0       9047.0          1831.0   
10935    -120.87     41.54                21.0       1091.0           208.0   
...          ...       ...                 ...          ...             ...   
16988    -124.21     41.75                20.0       3810.0           787.0   
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   

       population  households  median_income  median_house_value        mult  
10315       434.0       178.0         2.0903             56100.0    355010.0  
10348       976.0       403.0         2.6062             52600.0   1452300.0  
10620       429.0       181.0         2.0227             47500.0    388228.0  
10656      4276.0      1622.0         2.0802             47900.0  16565057.0  
10935       660.0       188.0         2.2321             34600.0    226928.0  
...           ...         ...            ...                 ...         ...  
16988      1993.0       721.0         2.0074             66900.0   2998470.0  
16990      1530.0       653.0         1.7038             78300.0   2099097.0  
16991      1343.0       479.0         2.4805             73200.0   1945944.0  
16997      1244.0       456.0         3.0313            103600.0   1421487.0  
16998      1298.0       478.0         1.9797             85800.0   1474944.0  

[65 rows x 10 columns]

In [ ]:
df.groupby(['housing_median_age']).mean()

longitude   latitude  total_rooms  total_bedrooms  \
housing_median_age                                                       
1.0                -121.465000  37.940000  2158.000000      335.500000   
2.0                -119.035306  35.410816  5237.102041      871.448980   
3.0                -118.798478  35.164783  6920.326087     1190.826087   
4.0                -118.805093  34.987764  6065.614907     1068.192547   
5.0                -118.789497  35.095327  4926.261307      910.924623   
6.0                -118.915969  35.183798  4365.062016      821.550388   
7.0                -119.165497  35.627616  5672.907285     1047.350993   
8.0                -119.375056  35.785899  4076.786517      779.252809   
9.0                -119.324186  35.654942  3813.465116      727.401163   
10.0               -119.350841  35.881681  3518.482301      681.508850   
11.0               -119.517837  35.930288  3971.105769      768.932692   
12.0               -119.405000  35.806458  4216.661458      838.843750   
13.0               -119.406586  35.814819  3692.506024      719.670683   
14.0               -119.510605  35.905159  3720.348703      719.187320   
15.0               -119.471490  35.878341  3283.317308      645.492788   
16.0               -119.530094  35.685748  3047.636220      593.274016   
17.0               -119.597656  35.907882  3133.967014      634.760417   
18.0               -119.640209  35.938054  3098.443515      624.525105   
19.0               -119.541820  35.842597  3005.140777      621.519417   
20.0               -119.862350  36.136449  2852.334204      601.778068   
21.0               -119.560134  35.751635  3134.273458      645.608579   
22.0               -119.598266  35.772879  3316.916409      683.736842   
23.0               -119.590890  35.718115  2918.803665      584.424084   
24.0               -119.344910  35.391054  2894.146530      604.647815   
25.0               -119.426898  35.470108  2797.260304      581.260304   
26.0               -119.477654  35.507038  2612.409543      523.944334   
27.0               -119.708363  35.707128  2577.405542      539.969773   
28.0               -119.568050  35.571075  2538.380000      540.707500   
29.0               -119.360348  35.427968  2484.064171      528.454545   
30.0               -119.499922  35.476120  2346.848958      511.291667   
31.0               -119.412865  35.370990  2345.164062      507.812500   
32.0               -119.465917  35.472664  2355.899563      489.515284   
33.0               -119.394211  35.402378  2205.391813      453.594542   
34.0               -119.195714  35.174603  2132.629630      434.989418   
35.0               -119.233786  35.163627  1969.802023      404.176301   
36.0               -119.232434  35.127972  1845.716084      377.085315   
37.0               -119.464371  35.335378  1819.633867      387.194508   
38.0               -119.334245  35.325472  1848.987421      402.591195   
39.0               -119.621556  35.513146  1886.930464      413.145695   
40.0               -119.576386  35.466265  1823.562249      408.236948   
41.0               -119.390086  35.316983  1653.521552      375.896552   
42.0               -119.480292  35.361169  1750.376623      396.230519   
43.0               -119.689301  35.582587  1683.895105      382.811189   
44.0               -119.460034  35.276351  1785.672297      382.351351   
45.0               -119.668596  35.468979  1790.889362      376.055319   
46.0               -119.877755  35.732194  1737.520408      389.678571   
47.0               -119.985029  35.843943  1780.457143      388.200000   
48.0               -119.837556  35.730222  1777.496296      379.400000   
49.0               -120.374324  36.097748  1928.369369      403.855856   
50.0               -120.077143  35.900893  1758.937500      394.687500   
51.0               -120.593750  36.325938  1871.562500      389.656250   
52.0               -120.917253  36.634230  1868.242395      404.811787   

                     pop

In [ ]:
ti=df.groupby(['total_bedrooms','total_rooms']).groups

In [ ]:
ti

{(1.0, 8.0): [16309], (2.0, 2.0): [2990], (3.0, 15.0): [15656], (3.0, 18.0): [2907], (3.0, 26.0): [9425], (3.0, 30.0): [1820], (4.0, 12.0): [15369], (4.0, 18.0): [14105], (4.0, 20.0): [12238], (4.0, 28.0): [10911], (4.0, 30.0): [14501], (4.0, 32.0): [13747], (5.0, 15.0): [4502], (5.0, 20.0): [3275], (5.0, 25.0): [1466], (5.0, 50.0): [13531], (6.0, 18.0): [8232], (6.0, 24.0): [2889, 11715], (6.0, 44.0): [15694], (6.0, 48.0): [6030], (7.0, 22.0): [5955], (7.0, 49.0): [9670], (7.0, 56.0): [1559], (7.0, 70.0): [8170], (8.0, 40.0): [4542], (8.0, 48.0): [10356], (9.0, 32.0): [3049], (9.0, 36.0): [5850], (9.0, 50.0): [2159], (9.0, 54.0): [8041, 15735], (9.0, 62.0): [2888], (9.0, 63.0): [2469], (10.0, 40.0): [5027, 9260, 11798], (10.0, 42.0): [288], (10.0, 50.0): [11458], (10.0, 60.0): [10146, 14034], (10.0, 80.0): [2273], (11.0, 11.0): [8188], (11.0, 37.0): [9191], (11.0, 45.0): [862, 3312], (11.0, 55.0): [9678], (11.0, 66.0): [15896], (11.0, 78.0): [606], (12.0, 51.0): [3446], (12.0, 60.0): 

In [ ]:
!pip install xlsxwriter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.8/152.8 KB 7.1 MB/s eta 0:00:00


In [ ]:
import xlsxwriter

In [ ]:
df=pd.DataFrame({'Data':[1,2,3,4,5]})
writer=pd.ExcelWriter('simple.xlsx',engine='xlsxwriter')
df.to_excel(writer,sheet_name='sheet1')
writer.close

<bound method ExcelWriter.close of <pandas.io.excel._xlsxwriter.XlsxWriter object at 0x7f091e66fc70>>

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
workbook=writer.book
worksheet=writer.sheets['sheet1']

In [ ]:
worksheet

In [ ]:
df.memory_usage()

Index                    128
longitude             136000
latitude              136000
housing_median_age    136000
total_rooms           136000
total_bedrooms        136000
population            136000
households            136000
median_income         136000
median_house_value    136000
mult                  136000
dtype: int64

### Swap two items

In [ ]:
letters[0], letters[1] = letters[1], letters[0]
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

### Removing items from a list

#### Pop from the end

In [ ]:
letters = ['a', 'b', 'c', 'd', 'e', 'f']
letters.pop()
letters

['a', 'b', 'c', 'd', 'e']

#### Pop by index

In [ ]:
letters.pop(2)
letters

['a', 'b', 'd', 'e']

#### Remove specific item

In [ ]:
letters.remove('d')
letters

['a', 'b', 'e']

### Create tuple using brackets

In [ ]:
tup = (1, 2, 3)
tup

(1, 2, 3)

### Create tuple with commas

In [ ]:
tup = 1, 2, 3
tup

(1, 2, 3)

### Create empty tuple

In [ ]:
tup = ()
tup

()

### Create tuple with single item

In [ ]:
tup = 1,
tup

(1,)

### Behaviours shared by lists and tuples
The following sequence behaviors are shared by lists and tuples

### Check item in sequence

In [ ]:
3 in (1, 2, 3, 4, 5)

True

### Check item not in sequence

In [ ]:
'a' not in [1, 2, 3, 4, 5]

True

### Slicing

#### Setting start, slice to the end

In [ ]:
letters = 'a', 'b', 'c', 'd', 'e', 'f'
letters[3:4]


('d',)

#### Set end, slice from beginning

In [ ]:
letters[:4]

('a', 'b', 'c', 'd')

#### Index from end of sequence

In [ ]:
letters[-4:]

('c', 'd', 'e', 'f')

#### Setting step

In [ ]:
letters[1::-2]

('b',)

### Unpacking

In [ ]:
first, middle = [1, 2, 3]

f"first = {first},  middle = {middle},  last = {last}"

ValueError: ignored

### Extended unpacking

In [ ]:
first, *middle, last = (1, 2, 3, 4, 5)

f"first = {first},  middle = {middle},  last = {last}"

'first = 1,  middle = [2, 3, 4],  last = 5'

### Using list as Stack
A stack is a LIFO (last in, first out) data structure which can be simulated using a list

#### Push onto the stack using append

In [ ]:
stack = []
stack.append('first on')
stack.append('second on')
stack.append('third on')
stack

['first on', 'second on', 'third on']

#### Retrieve items, last one first using **pop**

In [ ]:
f"Retrieved first: {stack.pop()!r}, retrieved second: {stack.pop()!r}, retrieved last: {stack.pop()!r}"

"Retrieved first: 'third on', retrieved second: 'second on', retrieved last: 'first on'"

## 5.2 Explore dictionaries 
Dictionaries are mappings of key value pairs.

### Create an empty dict using constructor

In [ ]:
dictionary = {}
dictionary

{}

### Create a dictionary based on key/value pairs

In [ ]:
key_values = [['key-1','value-1'], ['key-2', 'value-2']]
dictionary = dict(key_values)
dictionary

{'key-1': 'value-1', 'key-2': 'value-2'}

### Create an empty dict using curley braces

In [ ]:
dictionary = {}
dictionary

{}

### Use curley braces to create a dictionary with initial key/values

In [ ]:
dictionary = {'key-1': 'value-1',
              'key-2': 'value-2'}

dictionary

{'key-1': 'value-1', 'key-2': 'value-2'}

### Access value using key

In [ ]:
dictionary['key-1']

'value-1'

### Add a key/value pair to an existing dictionary

In [ ]:
dictionary['key-3'] = 'value-3'

dictionary

{'key-1': 'value-1', 'key-2': 'value-2', 'key-3': 'value-3'}

### Update value for existing key

In [ ]:
dictionary['key-2'] = 'new-value-2'
dictionary['key-2']

'new-value-2'

### Get keys

In [ ]:
list(dictionary.keys())

['key-1', 'key-2', 'key-3']

### Get values

In [ ]:
dictionary.values()

dict_values(['value-1', 'new-value-2', 'value-3'])

### Get iterable keys and items

In [ ]:
dictionary.items()

dict_items([('key-1', 'value-1'), ('key-2', 'new-value-2'), ('key-3', 'value-3')])

### Use items in for loop

In [ ]:
for key, value in dictionary.items():
  print(f"{key}: {value}")

key-1: value-1
key-2: new-value-2
key-3: value-3


### Check if dictionary has key
The 'in' syntax we used with sequences checks the dicts keys for membership.

In [ ]:
'key-5' in dictionary

False

### Get method

In [ ]:
dictionary.get("bad key", "default value")

'default value'

### Remove item

In [ ]:
del(dictionary['key-1'])
dictionary

{'key-2': 'new-value-2', 'key-3': 'value-3'}

### Keys must be immutable

#### List as key
Lists are mutable and not hashable

In [ ]:
items = ['item-1', 'item-2', 'item-3']

map = {}

map[items] = "some-value"

TypeError: ignored

#### Tuple as a key
Tuples are immutable and hence hashable

In [ ]:
items = 'item-1', 'item-2', 'item-3'
map = {}
map[items] = "some-value"

map

{('item-1', 'item-2', 'item-3'): 'some-value'}

## 5.3 Dive into sets

### Create set from tuple or list

In [ ]:
letters = 'a', 'a', 'a', 'b', 'c'
unique_letters = set(letters)
unique_letters

{'a', 'b', 'c'}

### Create set from a string

In [ ]:
unique_chars = set('mississippi')
unique_chars

{'i', 'm', 'p', 's'}

### Create set using curley braces

In [ ]:
unique_num = {1, 1, 2, 3, 4, 5, 5}
unique_num

{1, 2, 3, 4, 5}

### Adding to a set

In [ ]:
unique_num.add(6)
unique_num

{1, 2, 3, 4, 5, 6}

### Popping from a set
Pop method removes and returns a random element of the set

In [ ]:
unique_num.pop()

2

### Indexing
Sets have no order, and hence cannot be accessed via indexing

In [ ]:
unique_num[4]

TypeError: ignored

### Checking membership

In [ ]:
3 in unique_num

True

### Set operations

In [ ]:
s1 = { 1 ,2 ,3 ,4, 5, 6, 7}
s2 = { 0, 2, 4, 6, 8 }

#### Items in first set, but not in the second

In [ ]:
s1 - s2

{1, 3, 5, 7}

#### Items in either or both sets

In [ ]:
s1 | s2

{0, 1, 2, 3, 4, 5, 6, 7, 8}

#### Items in both sets

In [ ]:
s1 & s2

{2, 4, 6}

#### Items in either set, but not both

In [ ]:
s1 ^ s2

{0, 1, 3, 5, 7, 8}

## 5.4 Work with the numpy array


Numpy is an opened source numerical computing libary for python. The numpy array is a datastructure representing multidimension arrays which is optimized for both memory and performance.

### Create a numpy array from a list of lists

In [ ]:
import numpy as np
list_of_lists = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

np_array = np.array(list_of_lists)

np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Initialize an array of zeros

In [ ]:
zeros_array = np.zeros( (4, 5) )
zeros_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Initialize and array of ones

In [ ]:
ones_array = np.ones( (6, 6) )
ones_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### Using arrange

In [ ]:
nine = np.arange( 9 )
nine

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Using reshape

In [ ]:
nine.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Introspection

#### Get the data type

In [ ]:
np_array.dtype

dtype('int64')

#### Get the array's shape

In [ ]:
np_array.shape

(4, 4)

#### Get the number of items in the array

In [ ]:
np_array.size

16

#### Get the size of the array in bytes

In [ ]:
np_array.nbytes

128

### Setting the data type

#### dtype parameter

In [ ]:
np_array = np.array(list_of_lists, dtype=np.int8)
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int8)

#### Size reduction

In [ ]:
np_array.nbytes

16

#### The data type setting is immutible 
Data may be truncated if the data type is restrictive.

In [ ]:
np_array[0][0] = 1.7344567
np_array[0][0]

1

### Array Slicing


*   Slicing can be used to get a view reprsenting a sub-array. 
*   The slice is a view to the original array, the data is not copied to a new data structure
*   The slice is taken in the form: array[ rows, columns ]






In [ ]:
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int8)

In [ ]:
np_array[2:, :3]

array([[ 9, 10, 11],
       [13, 14, 15]], dtype=int8)

### Math operations


*   Unlike a unlike nested lists, matrix operations perform mathimatical operations on data



#### Create two 3 x 3 arrays

In [ ]:
np_array_1 = np.arange(9).reshape(3,3)
np_array_1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np_array_2 = np.arange(10, 19).reshape(3,3)
np_array_2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

#### Multiply the arrays

In [ ]:
np_array_1 * np_array_2

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

#### Add the arrays

In [ ]:
np_array_1 + np_array_2

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

### Matrix operations

#### Transpose

In [ ]:
np_array.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]], dtype=int8)

#### Dot product

In [ ]:
np_array_1.dot(np_array_2)


array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

## 5.5 Use the Pandas DataFrame
*   One of the most highly leveraged data structures for data science
*   A table-like two dimensional data structure. 


### Create a DataFrame

In [ ]:
import pandas as pd
first_names = ['henry', 'rolly', 'molly', 'frank', 'david', 'steven', 'gwen', 'arthur']
last_names = ['smith', 'brocker', 'stein', 'bach', 'spencer', 'de wilde', 'mason', 'davis']
ages = [43, 23, 78, 56, 26, 14, 46, 92]

df = pd.DataFrame({ 'first': first_names, 'last': last_names, 'age': ages})
df

age   first      last
0   43   henry     smith
1   23   rolly   brocker
2   78   molly     stein
3   56   frank      bach
4   26   david   spencer
5   14  steven  de wilde
6   46    gwen     mason
7   92  arthur     davis

### Head - looking at the top

In [ ]:
df.head(10)

age   first      last
0   43   henry     smith
1   23   rolly   brocker
2   78   molly     stein
3   56   frank      bach
4   26   david   spencer
5   14  steven  de wilde
6   46    gwen     mason
7   92  arthur     davis

### Setting number of rows returned with head

In [ ]:
df.head(3)

### Tail - looking at the bottom

In [ ]:
df.tail(2)

age   first   last
6   46    gwen  mason
7   92  arthur  davis

### Describe - descriptive statistics

In [ ]:
df.describe()

age
count   8.000000
mean   47.250000
std    27.227874
min    14.000000
25%    25.250000
50%    44.500000
75%    61.500000
max    92.000000

### Access one column

In [ ]:
df['first']

0     henry
1     rolly
2     molly
3     frank
4     david
5    steven
6      gwen
7    arthur
Name: first, dtype: object

### Slice a column

In [ ]:
df['first'][4:]

4     david
5    steven
6      gwen
7    arthur
Name: first, dtype: object

### Use conditions to filter

In [ ]:
df[df['age'] > 50]

age   first   last
2   78   molly  stein
3   56   frank   bach
7   92  arthur  davis

## 5.6 Use the pandas Series


*   A one dimensional labeled array
*   Contains data of only one type
*   Similar to a column in a spreedsheet




### Create a series

In [ ]:
pd_series = pd.Series( [1, 2, 3 ] )
pd_series

0    1
1    2
2    3
dtype: int64

### Series introspection methods

In [ ]:
f"This series is made up of {pd_series.size} items whose data type is {pd_series.dtype}"

'This series is made up of 3 items whose data type is int64'

### A Pandas DataFrame is composed of Pandas Series. 

In [ ]:
age = df.age
type( age )

pandas.core.series.Series

### Some useful helper methods of a Series

#### mean

In [ ]:
pd_series = pd.Series([ 1, 2, 3, 5, 6, 6, 6, 7, 8])
pd_series.mean()

4.888888888888889

#### Unique

In [ ]:
pd_series.unique()

array([1, 2, 3, 5, 6, 7, 8])

#### Max

In [ ]:
pd_series.min()

1

# Notes:
[Lists](https://docs.python.org/3/tutorial/datastructures.html)

[Tuples and sequences](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences)

[Dictionaries](https://docs.python.org/3/tutorial/datastructures.html#dictionaries)

[Numpy arrays](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)

[Pandas DataFrame](https://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.DataFrame.html)

[Pandas Series](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.Series.html)

